import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,reducedMotion:'reduce'});
const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
const b=(name)=>p.getByRole('button',{name,exact:true});
const d=(name)=>p.getByRole('dialog',{name,exact:true});
const check=async(name,fn)=>{await fn();console.log('PASS',name);};
const shot=process.env.QA_DIR||'/tmp/lead-radar-browser-qa';await fs.mkdir(shot,{recursive:true});
try {
await p.goto(process.env.BASE_URL||'http://127.0.0.1:3105/');
await b('体验示例数据').click();await p.getByText('0 位用户已选择',{exact:true}).waitFor();
await check('默认 A/B 且无人选中',async()=>{assert.equal(await p.locator('tbody tr').count(),4);assert.equal(await p.locator('tbody input:checked').count(),0);});
await b('待判断').click();assert.equal(await p.locator('tbody tr').count(),1);
await b('处理失败').click();assert.equal(await p.locator('tbody tr').count(),1);
await b('A/B 潜客').click();await b('详情').first().click();await d('小满今天早睡').getByText('人工调整记录',{exact:true}).waitFor();await d('小满今天早睡').getByRole('button',{name:'关闭面板'}).click();
await check('人工调整必须有原因并可追溯',async()=>{await p.getByLabel('调整 小满今天早睡 的等级').selectOption('B');assert.equal(await d('调整意向等级').getByRole('button',{name:'保存调整'}).isEnabled(),false);await p.getByLabel('调整原因').fill('近期计划仍需了解');await b('保存调整').click();await b('详情').first().click();await d('小满今天早睡').getByText(/近期计划仍需了解/).waitFor();await d('小满今天早睡').getByRole('button',{name:'关闭面板'}).click();});
await b('账号与规则').click();await p.getByLabel('流程模式').selectOption('formal');await b('保存并返回').click();
await p.getByLabel('选择 小满今天早睡',{exact:true}).check();await b('生成沟通内容').click();await d('账号与规则').waitFor();
await check('正式身份为空阻止生成',async()=>{assert.equal(await d('发送前确认').isVisible(),false);assert.equal(await p.getByLabel('真实对外身份',{exact:true}).inputValue(),'');});
await p.getByLabel('流程模式').selectOption('demo');await p.getByLabel('启用小红书演示账号').uncheck();await b('保存并返回').click();
await b('生成沟通内容').click();await d('发送前确认').waitFor();
await check('账号修复回到原草稿',async()=>{await p.getByLabel('小满今天早睡的拟发送内容',{exact:true}).fill('人工编辑的演示正文');await b('去设置').click();await p.getByLabel('启用小红书演示账号').check();await b('保存并返回').click();assert.equal(await p.getByLabel('小满今天早睡的拟发送内容',{exact:true}).inputValue(),'人工编辑的演示正文');});
await b('重新生成示例').click();await b('取消，保留编辑').click();assert.equal(await p.getByLabel('小满今天早睡的拟发送内容',{exact:true}).inputValue(),'人工编辑的演示正文');
await d('发送前确认').getByRole('button',{name:'关闭面板'}).click();await p.reload();await b('触达与跟进').click();await b('继续确认').click();
await check('刷新恢复草稿与配置',async()=>assert.equal(await p.getByLabel('小满今天早睡的拟发送内容',{exact:true}).inputValue(),'人工编辑的演示正文'));
await p.screenshot({path:shot+'/review.png',fullPage:true});
await b('确认发送 1 条').click();await p.getByText('回复检查：未启用',{exact:true}).waitFor();
await p.locator('summary').filter({hasText:'小满今天早睡'}).click();
await check('首轮提交不是发送成功且没有默认监控',async()=>{assert.equal(await b('模拟新回复').isEnabled(),false);assert.equal(await b('模拟发送成功').isVisible(),true);});
await b('模拟结果待核实').click();assert.equal(await b('确认已修复并重试').count(),0);await b('模拟核实为未发送').click();await b('确认已修复并重试').click();await b('模拟发送成功').click();
await b('历史名单').click();await p.getByLabel('筛选平台').selectOption('小红书');await p.getByLabel('筛选地区').selectOption('上海');await p.getByLabel('筛选联系状态').selectOption('已联系');assert.equal(await p.locator('tbody tr').count(),1);await b('原会话').click();await d('会话详情').getByText('首轮：发送成功（模拟）',{exact:true}).waitFor();await d('会话详情').getByRole('button',{name:'关闭面板'}).click();
await b('清空条件').click();await p.getByLabel('选择 养乐多不要冰',{exact:true}).check();
await check('导出已选与筛选范围一致',async()=>{await b('导出').click();await d('导出名单').getByLabel(/已选用户/).check();const ev=p.waitForEvent('download');await b('导出 1 位用户').click();const download=await ev;const csv=await fs.readFile(await download.path(),'utf8');assert.ok(csv.includes('养乐多不要冰'));assert.ok(!csv.includes('小满今天早睡'));await b('导出').click();await d('导出名单').getByLabel(/当前筛选结果/).check();assert.equal(await b('导出 4 位用户').isEnabled(),true);await d('导出名单').getByRole('button',{name:'关闭面板'}).click();});
await b('生成沟通内容').click();await d('发送前确认').getByLabel('启用后续回复检查',{exact:true}).check();assert.equal(await b('确认发送 1 条').isEnabled(),false);await p.getByLabel('检查间隔',{exact:true}).fill('30');assert.equal(await b('确认发送 1 条').isEnabled(),false);await p.getByLabel('检查截止时间',{exact:true}).fill('2099-01-01T12:00');await b('确认发送 1 条').click();
await b('模拟新回复').last().isDisabled();await p.locator('summary').filter({hasText:'养乐多不要冰'}).click();await b('模拟发送成功').click();await b('模拟检查无新回复').last().click();await b('模拟新回复').last().click();await b('处理这条回复').click();await p.getByLabel('拟回复内容',{exact:true}).fill('手动跟进草稿');await d('确认跟进回复').getByRole('button',{name:'关闭面板'}).click();
await p.reload();await b('触达与跟进').click();await p.locator('summary').filter({hasText:'养乐多不要冰'}).click();await b('处理这条回复').click();assert.equal(await p.getByLabel('拟回复内容',{exact:true}).inputValue(),'手动跟进草稿');await b('确认提交回复').click();
await check('跟进提交保留待办直到得到发送结果',async()=>{await p.getByText('跟进：待执行 · 待办未完成',{exact:true}).waitFor();await b('模拟发送成功').click();await p.getByText('跟进：发送成功 · 已回复',{exact:true}).waitFor();});
await b('打开会话详情').last().click();await b('暂停回复检查').click();await d('会话详情').getByText('回复检查：已暂停',{exact:true}).waitFor();await b('恢复回复检查').click();await b('结束回复检查').click();await d('会话详情').getByText('回复检查：已结束',{exact:true}).waitFor();await d('会话详情').getByRole('button',{name:'关闭面板'}).click();
await p.screenshot({path:shot+'/workflow.png',fullPage:true});
await b('历史名单').click();await p.screenshot({path:shot+'/history.png',fullPage:true});
await p.setViewportSize({width:390,height:844});await p.screenshot({path:shot+'/mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS browser flow; no page errors');
} finally {await browser.close();}
