import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyMonitoring,monitorError,monitorStatus,canGenerate,adjustGrade,transitionSend,contactStatus,exportRows,csvCell,taskStatus,todoStatus,beijingTime,accountStates} from '../app/operations-state.ts';
test('monitoring is off with no implicit interval',()=>{assert.equal(emptyMonitoring().enabled,false);assert.equal(emptyMonitoring().interval,'');assert.equal(monitorError(emptyMonitoring()),'');});
test('monitor interval and Beijing deadline are bounded',()=>{const now=Date.parse('2026-09-08T00:00:00Z');const m={...emptyMonitoring(),enabled:true,interval:'30',deadline:'2026-09-08T09:00'};assert.equal(monitorError(m,now),'');m.interval='60';assert.equal(monitorError(m,now),'');m.interval='15';assert.ok(monitorError(m,now));m.interval='30';m.deadline='2026-09-08T08:00';assert.ok(monitorError(m,now));m.deadline='2026-09-15T08:00';assert.equal(monitorError(m,now),'');m.deadline='2026-09-15T08:01';assert.ok(monitorError(m,now));assert.equal(beijingTime('2026-09-08T08:00'),now);});
test('monitoring expiry overrides pause and never auto extends',()=>{const m={...emptyMonitoring(),enabled:true,paused:true,deadline:'2000-01-01'};assert.equal(monitorStatus(m),'已到期');m.ended=true;assert.equal(monitorStatus(m),'已结束');});
test('an active reply check has its own non-repeatable state',()=>{const now=Date.parse('2026-09-08T00:00:00Z');const m={...emptyMonitoring(),enabled:true,interval:'30',deadline:'2026-09-09T08:00',checking:true};assert.equal(monitorStatus(m,now),'检查中');});
test('formal identity cannot use empty or demo identity',()=>{assert.equal(canGenerate('formal','',true),false);assert.equal(canGenerate('formal','咨询团队（示例）',true),false);assert.equal(canGenerate('formal','某机构',false),false);assert.equal(canGenerate('formal','某机构',true),true);assert.equal(canGenerate('demo','',false),true);});
test('grade changes require reason and retain previous conclusion',()=>{assert.throws(()=>adjustGrade('A','B',' '));const r=adjustGrade('A','B','需求尚不明确');assert.equal(r.from,'A');assert.equal(r.to,'B');assert.ok(r.time);assert.ok(r.actor);});
test('unknown results cannot be retried',()=>{assert.equal(transitionSend('结果待核实','retry'),'结果待核实');assert.equal(transitionSend('结果待核实','verified-failure'),'发送失败');assert.equal(transitionSend('发送失败','retry'),'待执行');});
test('success cannot be retried or canceled retroactively',()=>{assert.equal(transitionSend('发送成功','retry'),'发送成功');assert.equal(transitionSend('发送成功','cancel'),'发送成功');});
test('submission is not success; cancellation preserves its fact',()=>{assert.equal(contactStatus(['待执行']),'待执行');assert.equal(contactStatus(['发送成功']),'已联系');assert.equal(contactStatus(['发送失败']),'发送失败');assert.equal(contactStatus(['已取消']),'已取消');});
test('export scopes do not confuse selected with visible rows',()=>{const rows=[{id:1},{id:2},{id:3}];assert.deepEqual(exportRows('selected',rows,[2],[rows[0]]),[{id:2}]);assert.deepEqual(exportRows('filtered',rows,[2],[rows[0]]),[{id:1}]);assert.deepEqual(exportRows('selected',rows,[],rows),[]);});
test('CSV escapes quotation and spreadsheet formulas',()=>{assert.equal(csvCell('a"b'),'"a""b"');assert.equal(csvCell('=1+1'),'"\'=1+1"');});

test('task summaries follow explicit mixed-result precedence',()=>{for(const [r,p,a,want] of [[['待执行'],false,false,'待执行'],[['执行中'],false,false,'执行中'],[['发送成功','待执行'],false,false,'执行中'],[['待执行'],true,false,'已暂停'],[['待执行'],true,true,'异常暂停'],[['结果待核实','待执行'],true,true,'有待核实项'],[['发送成功','发送失败'],false,false,'部分完成'],[['发送成功'],false,false,'已完成'],[['已取消'],false,false,'已取消'],[['发送失败','已取消'],false,false,'已结束']])assert.equal(taskStatus(r,p,a),want);});
test('todos complete only on success and retain failure, unknown or handoff',()=>{assert.equal(todoStatus(),'待处理');assert.equal(todoStatus(undefined,'处理中'),'处理中');assert.equal(todoStatus(undefined,'待确认'),'待确认');assert.equal(todoStatus('待执行'),'等待发送结果');assert.equal(todoStatus('发送失败'),'发送失败');assert.equal(todoStatus('结果待核实'),'结果待核实');assert.equal(todoStatus('发送成功'),'已完成');assert.equal(todoStatus('发送失败','已关闭'),'已关闭');assert.equal(todoStatus(undefined,'已转人工'),'已转人工');});
test('account states are explicit and execution cannot be cancelled after starting',()=>{assert.deepEqual(accountStates,['未授权','授权中','正常','已失效','受限','连接异常']);assert.equal(transitionSend('待执行','start'),'执行中');assert.equal(transitionSend('执行中','cancel'),'执行中');assert.equal(transitionSend('执行中','unknown'),'结果待核实');});
