import type { Prospect as Lead } from './operations-state';
export const demoLeads: Lead[] = [
  { id: 7, name: '提问样本', handle: 'demo_07', grade: '待判断', score: 0, intent: '上下文不足', context: '这个可以吗？', evidence: '缺少所指对象与父评论，无法判断需求', location: '未知', status: '', source: '小红书评论', accountId: '', message: '' },
  { id: 8, name: '异常样本', handle: 'demo_08', grade: '待判断', score: 0, intent: '内容未读出', context: '', evidence: '该条处理失败，尚未形成分类结果', location: '未知', status: '', source: '小红书评论', accountId: '', message: '' },
  { id: 5, name: '晚风散步', handle: 'demo_05', grade: 'C', score: 35, intent: '日常互动', context: '谢谢分享，先收藏啦。', evidence: '仅收藏互动，未表达个人项目需求', location: '未知', status: '', source: '小红书评论', accountId: '', message: '' },
  { id: 6, name: '项目推广示例', handle: 'demo_06', grade: 'D', score: 12, intent: '推广信息', context: '本月活动，欢迎咨询合作。', evidence: '商业推广内容，不是消费者需求', location: '未知', status: '', source: '小红书评论', accountId: '', message: '' },
  {
    id: 1,
    name: '小满今天早睡',
    handle: 'src_71•••9a',
    grade: 'A',
    score: 92,
    intent: '超声炮 / 面部提升',
    context: '想做超声炮，上海有推荐吗？主要想改善下颌线，最近正在看机构。',
    evidence: '明确项目 + 求机构推荐 + 近期决策',
    location: '上海',
    status: '待审核话术',
    source: '小红书评论',
    accountId: '待核验',
    message: '',
  },
  {
    id: 2,
    name: '养乐多不要冰',
    handle: 'src_b2•••41',
    grade: 'B',
    score: 88,
    intent: '法令纹填充',
    context: '法令纹填充到底选玻尿酸还是再生材料？预算一万左右，怕做完很假。',
    evidence: '项目明确 + 有预算 + 主动对比方案',
    location: '杭州',
    status: '账号已核验',
    source: '小红书评论',
    accountId: 'xhs_6•••27',
    message: '',
  },
  {
    id: 3,
    name: '月光小橘',
    handle: 'src_0e•••c8',
    grade: 'B',
    score: 76,
    intent: '双眼皮 / 恢复期',
    context: '想问问大家做完双眼皮多久能正常上班，看起来不那么肿？',
    evidence: '有项目意向 + 关注恢复，但地区与时间未知',
    location: '未知',
    status: '待账号核验',
    source: '小红书评论',
    accountId: '待核验',
    message: '',
  },
  {
    id: 4,
    name: '橘子汽水加冰',
    handle: 'src_33•••bf',
    grade: 'B',
    score: 71,
    intent: '皮秒 / 痘印',
    context: '皮秒去痘印真的有用吗？看到有人说要做好几次，有点拿不准。',
    evidence: '痛点明确 + 正在比较，但购买信号较弱',
    location: '南京',
    status: '暂缓跟进',
    source: '小红书评论',
    accountId: 'xhs_demo_04',
    message: '',
  },
];
